allow SHOESTRAP_* as arguments on command line

diff --git a/helpers/default b/helpers/default
--- a/helpers/default
+++ b/helpers/default
@@ -5,6 +5,34 @@
 ##############################################################################
 
 COOKBOOK_NAME="$(basename $0)"
+
+# Since running 'sudo <cookbook>' clobbers almost all environment variables,
+# this argument handling allows things like SHOESTRAP_BASE and SHOESTRAP_LOCAL
+# to be passed in as a command line argument.
+#
+# NOTE: The command line overrides the environment variable
+
+while [ -n "$1" ]; do
+    case "$1" in
+        SHOESTRAP_BASE=*)
+            SHOESTRAP_BASE="${1#SHOESTRAP_BASE=}"
+            shift
+            ;;
+        SHOESTRAP_LOCAL=*)
+            SHOESTRAP_LOCAL="${1#SHOESTRAP_LOCAL=}"
+            shift
+            ;;
+        --)
+            shift
+            break
+            ;;
+        *)
+            echo "Error parsing argument '$1'"
+            exit 1
+            ;;
+    esac
+done
+
 if [ -z "$SHOESTRAP_BASE" ]; then
     DIR="$( cd "$( dirname "$0" )" && pwd )"
 else
